import {drawTerrain} from './terrain.mjs';
import {PROP_TYPES,drawProp,depthOrder} from './scenery.mjs';
import {MAPS,ENEMY_SPAWNS,ENEMY_TYPES,portalsOf,RUNES,INSCRIPTION} from './world.mjs';
import {validateSettings} from './settings.mjs';
const $=id=>document.getElementById(id),canvas=$('mapCanvas'),ctx=canvas.getContext('2d'),copy=x=>structuredClone(x);
let draft,defaults,token,selected=0,history=[],future=[],drag=null,pending=[],dirty=false;
const propImages=Object.fromEntries(Object.entries(PROP_TYPES).map(([key,type])=>{const i=new Image();i.src='sprites/'+type.file;i.onload=draw;return [key,i];}));
const enemyImages=Object.fromEntries(Object.keys(ENEMY_TYPES).map(type=>{const i=new Image();i.src='sprites/'+type+'-topdown.png';i.onload=draw;return [type,i];}));
const images=MAPS.map(m=>{const i=new Image();i.src='sprites/'+m.image;i.onload=draw;return i;});
const map=()=>Number($('map').value),obstacles=()=>draft.maps[map()].obstacles,object=()=>obstacles()[selected];
function status(message,error=false){$('status').textContent=message;$('status').style.borderColor=error?'#ed806b':'#b9a070';}
function checkpoint(){history.push(copy(draft));if(history.length>80)history.shift();future=[];dirty=true;$('undo').disabled=false;$('redo').disabled=true;status('Modificações locais — clique em Salvar e aplicar para publicar.');}
function refresh(){if(!draft)return;$('objects').replaceChildren();obstacles().forEach((o,i)=>{const option=new Option(o.name,i);$('objects').add(option);});selected=Math.min(selected,obstacles().length-1);$('objects').value=selected;fields();draw();$('undo').disabled=!history.length;$('redo').disabled=!future.length;}
function fields(){const o=object();$('name').value=o?.name||'';$('points').value=o?.points.map(p=>p.join(', ')).join('\n')||'';}
function draw(){if(!draft)return;const s=canvas.width/2048;ctx.clearRect(0,0,1000,1000);if(images[map()].complete)ctx.drawImage(images[map()],0,0,1000,1000);ctx.save();ctx.scale(s,s);drawTerrain(ctx,map(),0,images[2]);if($('props').checked)for(const prop of depthOrder(MAPS[map()].props)){const img=propImages[prop.type];if(img.complete&&img.naturalWidth)drawProp(ctx,prop,img);}for(const enemy of ENEMY_SPAWNS.filter(e=>e.map===map())){const img=enemyImages[enemy.type];if(img.naturalWidth){const h=enemy.type==='titan'?420:enemy.type==='malenio'||enemy.type==='warden'?120:82,w=h*img.width/img.height;ctx.drawImage(img,enemy.x-w/2,enemy.y-h+8,w,h);}}if($('overlay').checked)obstacles().forEach((o,index)=>{ctx.beginPath();o.points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fillStyle=index===selected?'#f7c97055':'#ed655b40';ctx.strokeStyle=index===selected?'#ffe3a3':'#fa8e83';ctx.lineWidth=3/s;ctx.fill();ctx.stroke();if(index===selected)o.points.forEach(([x,y])=>{ctx.fillStyle='#fff1c4';ctx.fillRect(x-5/s,y-5/s,10/s,10/s);});});for(const [label,p] of [['Entrada',MAPS[map()].spawn],['Fogueira',MAPS[map()].camp],...portalsOf(map()).map(p=>[p.label,p]),...(map()===2?[...RUNES.map(r=>[r.label,r]),['Inscrição',INSCRIPTION]]:[]),...ENEMY_SPAWNS.filter(e=>e.map===map()).map(e=>[e.type,e])]){ctx.fillStyle=p.type?'#dab5ff':'#fff3ad';ctx.beginPath();ctx.arc(p.x,p.y,12,0,7);ctx.fill();ctx.font='24px system-ui';ctx.fillText(label,p.x+18,p.y);}if(pending.length){ctx.strokeStyle='#9cffcb';ctx.lineWidth=4;ctx.beginPath();pending.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.stroke();}ctx.restore();}
function pos(e){const r=canvas.getBoundingClientRect(),grid=Math.max(1,Math.min(128,Number($('grid').value)||1));return [e.clientX-r.left,e.clientY-r.top].map((n,i)=>Math.max(0,Math.min(2048,Math.round(n/(i?r.height:r.width)*2048/grid)*grid)));}
function contains(p,points){let hit=false;for(let i=0,j=points.length-1;i<points.length;j=i++){const a=points[i],b=points[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])hit=!hit;}return hit;}
canvas.onpointerdown=e=>{if(!draft)return;const p=pos(e),tool=$('tool').value;canvas.setPointerCapture(e.pointerId);if(tool==='poly'){pending.push(p);draw();return;}if(tool==='rect'){drag={tool,start:p};pending=[p,p];return;}const vertex=object()?.points.findIndex(q=>Math.hypot(q[0]-p[0],q[1]-p[1])<28)??-1;if(tool==='select'&&vertex>=0){checkpoint();drag={tool,vertex};return;}selected=obstacles().findLastIndex(o=>contains(p,o.points));refresh();if(tool==='move'&&object()){checkpoint();drag={tool,start:p,points:copy(object().points)};}};
canvas.onpointermove=e=>{if(!drag)return;const p=pos(e);if(drag.tool==='select')object().points[drag.vertex]=p;else if(drag.tool==='move'){const dx=p[0]-drag.start[0],dy=p[1]-drag.start[1];if(drag.points.every(q=>q[0]+dx>=0&&q[0]+dx<=2048&&q[1]+dy>=0&&q[1]+dy<=2048))object().points=drag.points.map(q=>[q[0]+dx,q[1]+dy]);}else{const [x,y]=drag.start;pending=[[x,y],[p[0],y],p,[x,p[1]],[x,y]];}fields();draw();};
canvas.onpointerup=e=>{if(drag?.tool==='rect'){const p=pos(e),a=drag.start;if(Math.abs(p[0]-a[0])>2&&Math.abs(p[1]-a[1])>2){checkpoint();obstacles().push({name:'Nova colisão',points:[a,[p[0],a[1]],p,[a[0],p[1]]]});selected=obstacles().length-1;}pending=[];}drag=null;refresh();};canvas.onpointercancel=()=>{drag=null;pending=[];refresh();};
$('finish').onclick=()=>{if(pending.length<3)return status('Marque pelo menos três vértices.',true);checkpoint();obstacles().push({name:'Novo polígono',points:copy(pending)});selected=obstacles().length-1;pending=[];refresh();};
$('map').onchange=()=>{selected=0;pending=[];refresh();};$('tool').onchange=()=>{pending=[];draw();};$('overlay').onchange=draw;$('props').onchange=draw;$('objects').onchange=()=>{selected=Number($('objects').value);fields();draw();};
$('update').onclick=()=>{if(!object())return;try{const next=copy(draft);next.maps[map()].obstacles[selected]={name:$('name').value,points:$('points').value.trim().split('\n').map(line=>line.trim().split(/[,\s]+/).map(Number))};validateSettings(next);checkpoint();draft=next;refresh();}catch(e){status(e.message,true);}};
$('delete').onclick=()=>{if(!object())return;checkpoint();obstacles().splice(selected,1);refresh();};$('duplicate').onclick=()=>{if(!object())return;checkpoint();const o=copy(object());o.name+=' cópia';o.points=o.points.map(p=>p.map(n=>Math.min(2048,n+24)));obstacles().push(o);selected=obstacles().length-1;refresh();};
$('undo').onclick=()=>{if(!history.length)return;future.push(copy(draft));draft=history.pop();dirty=true;refresh();difficulty();};$('redo').onclick=()=>{if(!future.length)return;history.push(copy(draft));draft=future.pop();dirty=true;refresh();difficulty();};
$('resetMap').onclick=()=>{checkpoint();draft.maps[map()]=copy(defaults.maps[map()]);refresh();};$('defaults').onclick=()=>{checkpoint();draft={...copy(defaults),revision:draft.revision};refresh();difficulty();};
const labels={hp:'Vida',speed:'Velocidade',range:'Alcance',damage:'Dano',windup:'Aviso (segundos)',cooldown:'Intervalo (segundos)',playerSpeed:'Velocidade do jogador',playerDamage:'Multiplicador de dano do jogador',aggroRange:'Distância de perseguição'};
function inputs(parent,data,keys){for(const key of keys){const label=document.createElement('label');label.textContent=labels[key];const input=document.createElement('input');input.type='number';input.step=['windup','cooldown','playerDamage'].includes(key)?'.05':'1';input.value=data[key];input.onchange=()=>{checkpoint();data[key]=Number(input.value);};label.append(input);parent.append(label);}}
function difficulty(){$('tuning').replaceChildren();inputs($('tuning'),draft.tuning,Object.keys(draft.tuning));$('enemies').replaceChildren();for(const [type,enemy] of Object.entries(draft.enemies)){const group=document.createElement('fieldset'),legend=document.createElement('legend'),stats=document.createElement('div');legend.textContent=enemy.name;stats.className='stats';group.append(legend,stats);inputs(stats,enemy,['hp','speed','range','damage','windup','cooldown']);$('enemies').append(group);}}
for(const button of document.querySelectorAll('[data-preset]'))button.onclick=()=>{checkpoint();draft.enemies=copy(defaults.enemies);draft.tuning=copy(defaults.tuning);const preset=button.dataset.preset;for(const e of Object.values(draft.enemies)){if(preset==='easy'){e.hp=Math.round(e.hp*.7);e.damage=Math.round(e.damage*.65);e.windup*=1.3;}if(preset==='hard'){e.hp=Math.round(e.hp*1.4);e.damage=Math.round(e.damage*1.3);e.windup*=.8;}}difficulty();};
$('save').onclick=async()=>{try{validateSettings(draft);$('save').disabled=true;const r=await fetch('/api/admin/settings',{method:'POST',headers:{'content-type':'application/json','x-admin-token':token},body:JSON.stringify(draft)}),data=await r.json();if(!r.ok)throw new Error(data.error);draft=data;history=[];future=[];dirty=false;refresh();difficulty();status('Configuração salva no servidor e aplicada às partidas.');}catch(e){status(e.message,true);}finally{$('save').disabled=false;}};
$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(draft,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='aurorabroken-config.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);};
$('import').onchange=async()=>{try{const file=$('import').files[0];if(!file)return;if(file.size>256000)throw new Error('Máximo 256 KB.');const data=validateSettings(JSON.parse(await file.text()));checkpoint();draft={...data,revision:draft.revision};refresh();difficulty();}catch(e){status(e.message,true);}};
async function load(){try{const r=await fetch('/api/admin/session',{cache:'no-store'}),data=await r.json();if(!r.ok)throw new Error(data.error);({token,defaults}=data);draft=data.settings;dirty=false;history=[];future=[];refresh();difficulty();status('Pronto. Selecione uma colisão ou ajuste a dificuldade.');}catch(e){$('save').disabled=true;status(e.message,true);}}
$('reload').onclick=load;addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});await load();
