import {MAPS,ENEMY_TYPES,blocked,safePoint,portalsOf} from './world.mjs';
import {inLava} from './terrain.mjs';
export const ATTRIBUTES={vitality:'Vitalidade',strength:'Força',focus:'Foco',vigor:'Vigor',fortune:'Fortuna'};
export const RARITIES=['Comum','Incomum','Raro','Épico','Lendário'];
export const BOSSES=['malenio','warden','titan'];
export const RELICS={malenio:'Lâmina do Sol Partido',warden:'Égide da Primeira Aurora',titan:'Coração de Asterion'};
export const finite=(n,max=1e100)=>Number.isFinite(n)?Math.max(0,Math.min(max,n)):0;
export const level=p=>1+Object.values(p.attributes||{}).reduce((a,b)=>a+b,0);
export const levelCost=p=>Math.ceil(40*Math.pow(level(p),1.55));
export const maxHealth=p=>100+12*(p.attributes?.vitality||0);
export const maxEnergy=p=>100+Math.min(400,3*(p.attributes?.vigor||0));
export function rng(seed){let a=seed>>>0;return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return ((t^t>>>14)>>>0)/4294967296;};}
export function initProgress(p){p.attributes=Object.fromEntries(Object.keys(ATTRIBUTES).map(k=>[k,0]));p.embers=0;p.inventory=[];p.lootGear={};p.bloodstain=null;p.bossClaims=[];p.maxHp=maxHealth(p);}
export function progressionStats(p){const gear=Object.values(p.lootGear||{}).map(id=>p.inventory?.find(i=>i.id===id)).filter(Boolean);return {power:1+gear.reduce((n,i)=>n+i.power,0),defense:Math.min(35,gear.reduce((n,i)=>n+i.defense,0)),solar:gear.some(i=>i.relic==='malenio'),ward:gear.some(i=>i.relic==='warden'),titan:gear.some(i=>i.relic==='titan')};}
export function itemFor(w,p,source,boss=null){const random=rng(w.seed+w.cycle*7919+(w.lootSerial++||0)*101+source.length*53),rarity=boss?4:Math.min(4,Math.floor(Math.pow(random(),Math.max(.25,1-(p.attributes.fortune||0)*.005))*4.15)),slots=['weapon','helmet','chest','gloves','legs','boots'],slot=boss?(boss==='malenio'?'weapon':boss==='warden'?'chest':'relic'):slots[Math.floor(random()*slots.length)],weapons=p.character==='witch'?['staff','wand','tome']:['sword','spear','axe'],rank=1+w.cycle*6+p.map,base=weapons[Math.floor(random()*3)];return {id:'loot-'+w.seed+'-'+w.cycle+'-'+w.lootSerial,slot,base:slot==='weapon'?base:null,character:p.character,rarity,rank,name:boss?RELICS[boss]:slot, power:Math.round((.025*rank*(rarity+1))*(slot==='weapon'?2:1)*1000)/1000,defense:slot==='weapon'||slot==='relic'?0:Math.min(9,(rarity+1)*.5+rank*.15),relic:boss};}
function grant(p,item){if(item.relic&&p.inventory.length>=120){const i=p.inventory.findIndex(a=>!Object.values(p.lootGear).includes(a.id)&&!a.relic);if(i>=0){const old=p.inventory.splice(i,1)[0];p.embers=finite(p.embers+Math.ceil(old.rank*(old.rarity+1)*20));}else{const i=p.inventory.findIndex(a=>!Object.values(p.lootGear).includes(a.id));if(i>=0)p.inventory.splice(i,1);}}if(p.inventory.length>=120){p.embers=finite(p.embers+Math.ceil(item.rank*(item.rarity+1)*20));p.message='Inventário cheio: item convertido em Brasas.';}else{p.inventory.push(item);p.message='Novo equipamento no inventário';}p.messageTime=5;}
export function rewardKill(w,e){for(const p of Object.values(w.players).filter(p=>p.map===e.map&&p.hp>0)){p.embers=finite(p.embers+Math.ceil((BOSSES.includes(e.type)?240:25)*(1+e.map)*Math.pow(1+w.cycle,2.2)));if(BOSSES.includes(e.type)){const key=w.cycle+':'+e.id;if(!p.bossClaims.includes(key)){p.bossClaims.push(key);grant(p,itemFor(w,p,e.id,e.type));}}}}
export function breakCrate(w,p,c){if(c.broken)return;c.broken=true;for(const a of Object.values(w.players).filter(a=>a.map===c.map&&a.hp>0)){a.embers=finite(a.embers+15*(1+c.map)*Math.pow(1+w.cycle,2));grant(a,itemFor(w,a,c.id));}w.effects.push({kind:'burst',x:c.x,y:c.y,range:35,map:c.map,color:'#dfad64',life:.3});}
export function die(p){p.bloodstain={map:p.map,x:p.x,y:p.y,amount:p.embers};p.embers=0;p.resting=false;}
export function recover(p){const b=p.bloodstain;if(b&&b.map===p.map&&Math.hypot(p.x-b.x,p.y-b.y)<50){p.embers=finite(p.embers+b.amount);p.bloodstain=null;p.message='Brasas recuperadas';p.messageTime=4;}}
export function createCrates(w){const result=[],random=rng(w.seed+w.cycle*4099);for(const m of MAPS){let count=0;for(let n=0;n<600&&count<9;n++){const x=160+random()*1728,y=180+random()*1690;if(blocked(m.id,x,y,35)||inLava(m.id,x,y)||Math.hypot(x-m.camp.x,y-m.camp.y)<140||Math.hypot(x-m.spawn.x,y-m.spawn.y)<140||portalsOf(m.id).some(p=>Math.hypot(x-p.x,y-p.y)<140)||m.id===2&&Math.abs(y-880)<100)continue;result.push({id:'box-'+m.id+'-'+count++,map:m.id,x,y,broken:false});}}return result;}
export function scaleEnemies(w){const random=rng(w.seed+w.cycle*7919);for(const e of w.enemies){const base=ENEMY_TYPES[e.type],factor=Math.pow(1+w.cycle,2.3);e.maxHp=Math.round(base.hp*factor);e.hp=e.maxHp;e.damage=Math.round(base.damage*Math.pow(1+w.cycle,.9));e.speed=base.speed*(1+Math.min(.35,w.cycle*.02));e.variant=w.cycle?['Feroz','Robusto','Ágil'][Math.floor(random()*3)]:'';if(e.variant==='Feroz')e.damage*=1.2;if(e.variant==='Robusto')e.hp=e.maxHp=Math.round(e.maxHp*1.25);if(e.variant==='Ágil')e.speed*=1.15;if(w.cycle&&!BOSSES.includes(e.type)){for(let n=0;n<15;n++){const x=e.homeX+(random()-.5)*180,y=e.homeY+(random()-.5)*180;if(!blocked(e.map,x,y,24)&&!inLava(e.map,x,y)&&!(e.map===2&&(y<880)!==(e.homeY<880))){e.x=e.homeX=x;e.y=e.homeY=y;break;}}}}}
export function atCamp(p){return p.hp>0&&Math.hypot(p.x-MAPS[p.map].camp.x,p.y-MAPS[p.map].camp.y)<130;}
export function progressionAction(w,p,action,value){if(!p||p.hp<=0)throw new Error('Você precisa estar vivo.');
 if(action==='equipItem'){const i=p.inventory.find(i=>i.id===value);if(!i||i.character!==p.character)throw new Error('Item inválido.');p.lootGear[i.slot]=i.id;if(i.slot==='weapon')p.equipment.weapon=i.base;return;}
 if(action==='unequipItem'){if(typeof value==='string')delete p.lootGear[value];return;}
 if(action==='dismantle'){const index=p.inventory.findIndex(i=>i.id===value);if(index<0||Object.values(p.lootGear).includes(value))throw new Error('Desequipe o item primeiro.');const i=p.inventory.splice(index,1)[0];p.embers=finite(p.embers+Math.ceil(i.rank*(i.rarity+1)*20));return;}
 if(action==='leaveCamp'){p.resting=false;return;}
 if(!p.resting||!atCamp(p))throw new Error('Sente na fogueira primeiro.');
 if(action==='level'){if(!Object.hasOwn(ATTRIBUTES,value))throw new Error('Atributo inválido.');if(value==='fortune'&&p.attributes[value]>=150||value==='vigor'&&p.attributes[value]>=134)throw new Error('Este atributo atingiu seu limite.');const cost=levelCost(p);if(p.embers<cost)throw new Error('Brasas insuficientes.');p.embers-=cost;p.attributes[value]++;p.maxHp=maxHealth(p);p.hp=p.maxHp;p.energy=maxEnergy(p);return;}
 if(action==='rest'){const players=Object.values(w.players);if(!players.every(a=>a.resting&&atCamp(a)&&a.map===p.map))throw new Error('Todos precisam sentar na mesma fogueira.');for(const e of w.enemies)if(e.map===p.map&&!BOSSES.includes(e.type)){e.hp=e.maxHp;e.x=e.homeX;e.y=e.homeY;e.state='idle';e.timer=0;}w.projectiles=w.projectiles.filter(s=>s.map!==p.map);for(const a of players){a.hp=a.maxHp;a.energy=maxEnergy(a);}return;}
 if(action==='cycle'){if(!w.won)throw new Error('Derrote Asterion antes da próxima jornada.');if(!Object.values(w.players).every(a=>a.resting&&atCamp(a)&&a.map===p.map))throw new Error('Todos precisam sentar na mesma fogueira.');return 'cycle';}
 throw new Error('Ação inválida.');
}
export function restoreProgress(p,saved){initProgress(p);for(const key of Object.keys(ATTRIBUTES))p.attributes[key]=Math.floor(finite(saved.attributes?.[key],1e9));p.embers=finite(saved.embers);const ids=new Set();p.inventory=(Array.isArray(saved.inventory)?saved.inventory:[]).slice(0,120).filter(i=>i&&typeof i.id==='string'&&i.id.length<100&&!ids.has(i.id)&&ids.add(i.id)&&['weapon','helmet','chest','gloves','legs','boots','relic'].includes(i.slot)&&i.character===p.character&&(i.slot!=='weapon'||(p.character==='witch'?['staff','wand','tome']:['sword','spear','axe']).includes(i.base))).map(i=>({id:i.id,slot:i.slot,base:i.base,character:p.character,name:typeof i.name==='string'?i.name.slice(0,80):i.slot,rarity:Math.floor(finite(i.rarity,4)),rank:Math.max(1,finite(i.rank)),power:finite(i.power),defense:finite(i.defense,9),relic:BOSSES.includes(i.relic)?i.relic:null}));for(const [slot,id] of Object.entries(saved.lootGear||{}))if(p.inventory.some(i=>i.id===id&&i.slot===slot))p.lootGear[slot]=id;
 p.bossClaims=(Array.isArray(saved.bossClaims)?saved.bossClaims:[]).filter(s=>typeof s==='string').slice(-100);const b=saved.bloodstain;if(b&&Number.isInteger(b.map)&&MAPS[b.map]&&Number.isFinite(b.x)&&Number.isFinite(b.y))p.bloodstain={map:b.map,...safePoint(b.map,b),amount:finite(b.amount)};p.maxHp=maxHealth(p);
}
export function progressRecord(p){return {campaignCycle:p.campaignCycle,attributes:p.attributes,embers:p.embers,inventory:p.inventory,lootGear:p.lootGear,bloodstain:p.bloodstain,bossClaims:p.bossClaims};}
