import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorld,addPlayer,attack,tick,interact,playerAction,respawn} from '../client/engine.mjs';
import {MAPS,blocked} from '../client/world.mjs';
import {inLava} from '../client/terrain.mjs';
import {levelCost,level,breakCrate,rewardKill,die,recover,maxEnergy} from '../client/progression.mjs';
import {equipmentStats} from '../client/equipment.mjs';
import {encodeSave,decodeSave} from '../client/save.mjs';
import {newRoom,joinProfile,hashToken,captureRoom,restoreRoom} from '../api/room-store.mjs';
const sit=(w,p)=>{Object.assign(p,MAPS[p.map].camp,{portalCd:0});interact(w,p);};
test('camp levels spend currency once, improve stats, gate actions and resume play',()=>{const w=createWorld(0,123),p=addPlayer(w,'a');p.embers=1000;assert.throws(()=>playerAction(w,p,'level','vitality'));sit(w,p);const cost=levelCost(p);playerAction(w,p,'level','vitality');assert.equal(p.embers,1000-cost);assert.equal(p.maxHp,112);assert.equal(p.hp,112);assert.equal(level(p),2);assert.throws(()=>playerAction(w,p,'level','bad'));p.embers=0;assert.throws(()=>playerAction(w,p,'level','focus'));const before={x:p.x,y:p.y};tick(w,{a:{up:true,attack:true}});assert.equal(p.x,before.x);assert.equal(p.y,before.y);playerAction(w,p,'leaveCamp');tick(w,{a:{up:true}});assert.notEqual(p.y,before.y);});
test('crates are deterministic, on safe terrain, break once and grant personal equipment',()=>{const w=createWorld(2,123),copy=createWorld(2,123),p=addPlayer(w,'a'),b=addPlayer(w,'b','witch');assert.deepEqual(w.crates,copy.crates);assert.ok(w.crates.length>=30);for(const c of w.crates){assert.equal(blocked(c.map,c.x,c.y,35),false);assert.equal(inLava(c.map,c.x,c.y),false);}const c=w.crates.find(c=>c.map===0);breakCrate(w,p,c);assert.equal(p.inventory.length,1);assert.equal(b.inventory[0].character,'witch');const amount=p.embers;breakCrate(w,p,c);assert.equal(p.embers,amount);const item=p.inventory[0],before=equipmentStats(p).power;playerAction(w,p,'equipItem',item.id);assert.ok(equipmentStats(p).power>before);assert.throws(()=>playerAction(w,p,'dismantle',item.id));playerAction(w,p,'unequipItem',item.slot);playerAction(w,p,'dismantle',item.id);assert.equal(p.inventory.length,0);assert.ok(p.embers>amount);});
test('every boss guarantees unique rare loot once in a cycle for each living participant',()=>{const w=createWorld(0,3),p=addPlayer(w,'a'),b=addPlayer(w,'b','witch');for(const type of ['malenio','warden','titan']){const boss=w.enemies.find(e=>e.type===type);p.map=b.map=boss.map;rewardKill(w,boss);const length=p.inventory.length;rewardKill(w,boss);assert.equal(p.inventory.length,length);assert.equal(p.inventory.at(-1).relic,type);assert.equal(p.inventory.at(-1).rarity,4);assert.equal(b.inventory.at(-1).character,'witch');}assert.equal(p.inventory.length,3);});
test('death drops only unspent embers, second death replaces loss, retrieval and respawn persist',()=>{const w=createWorld(0,123),p=addPlayer(w,'a');p.embers=420;p.attributes.vitality=2;die(p);assert.equal(p.embers,0);assert.equal(p.bloodstain.amount,420);p.x+=200;p.embers=7;die(p);assert.equal(p.bloodstain.amount,7);recover(p);assert.equal(p.embers,7);assert.equal(p.bloodstain,null);p.map=4;Object.assign(p,{x:50,y:50,embers:99,hp:1,invuln:0});tick(w,{},.05);assert.equal(p.hp,0);assert.equal(p.bloodstain.amount,99);p.checkpointMap=1;w.campfires[1]=true;respawn(w,p);assert.equal(p.map,1);assert.ok(Math.hypot(p.x-MAPS[1].camp.x,p.y-MAPS[1].camp.y)<130);assert.equal(p.bloodstain.map,4);});
test('rest renewal requires party consent, excludes bosses and boxes; cycles reset world and keep builds',()=>{const w=createWorld(0,123),p=addPlayer(w,'a'),b=addPlayer(w,'b');sit(w,p);const enemy=w.enemies[0];enemy.hp=0;assert.throws(()=>playerAction(w,p,'rest'));sit(w,b);const boss=w.enemies.find(e=>e.type==='malenio');boss.hp=0;w.crates[0].broken=true;playerAction(w,p,'rest');assert.equal(enemy.hp,enemy.maxHp);assert.equal(boss.hp,0);assert.equal(w.crates[0].broken,true);assert.throws(()=>playerAction(w,p,'cycle'));w.won=true;p.attributes.strength=8;p.embers=123;playerAction(w,p,'cycle');assert.equal(w.cycle,1);assert.equal(p.attributes.strength,8);assert.equal(p.embers,123);assert.equal(w.won,false);assert.ok(w.enemies[0].maxHp>enemy.maxHp);assert.ok(w.crates.every(c=>!c.broken));assert.equal(p.resting,false);assert.equal(p.map,0);});
test('solo and co-op saves roundtrip cycles, loot, attributes, lost embers and boxes; old saves migrate',()=>{const hash=hashToken('test'),room=newRoom(hash),p=joinProfile(room,'a',hash,'warrior','Test');p.embers=500;p.attributes.vigor=3;breakCrate(room.world,p,room.world.crates[0]);p.lootGear[p.inventory[0].slot]=p.inventory[0].id;die(p);const encoded=encodeSave(room.world,'a'),w=decodeSave(encoded);assert.deepEqual(w.players.solo.inventory,p.inventory);assert.deepEqual(w.players.solo.bloodstain,p.bloodstain);assert.equal(w.crates[0].broken,true);const restored=restoreRoom(captureRoom(room,'TEST'));assert.deepEqual(restored.profiles[hash].inventory,p.inventory);assert.deepEqual(restored.profiles[hash].attributes,p.attributes);assert.equal(restored.world.seed,room.world.seed);const old=JSON.parse(encoded);old.version=3;delete old.player.attributes;delete old.player.inventory;delete old.player.lootGear;assert.equal(level(decodeSave(JSON.stringify(old)).players.solo),1);const high=createWorld(10000,12);assert.ok(high.enemies.every(e=>Number.isFinite(e.hp)&&Number.isFinite(e.damage)));});

test('melee and projectiles break crates through the real combat loop',()=>{for(const kind of ['normal','ranged']){const w=createWorld(0,2),p=addPlayer(w,'a');w.enemies=[];Object.assign(p,{x:1040,y:1520,facingX:0,facingY:-1});w.crates=[{id:'combat-box',map:0,x:1040,y:1450,broken:false}];attack(w,p,kind);for(let n=0;n<30;n++)tick(w,{});assert.equal(w.crates[0].broken,true);assert.equal(p.inventory.length,1);}});
test('offline co-op profiles retain their build but return to the new journey entrance',()=>{const hash=hashToken('offline'),room=newRoom(hash),p=joinProfile(room,'a',hash,'warrior','Test');p.map=5;p.attributes.strength=25;captureRoom(room,'TEST');delete room.world.players.a;delete room.identities.a;room.world=createWorld(2,room.world.seed);const restored=restoreRoom(captureRoom(room,'TEST'));const joined=joinProfile(restored,'b',hash,'warrior','Test');assert.equal(joined.map,0);assert.equal(joined.attributes.strength,25);assert.equal(joined.campaignCycle,2);});
